name = "nnqs"
version = "1.0.5"
license = "MIT"
author = "Austin C Bullock, Andrew Wasserbeck"
maintainer = "acb.bullock@gmail.com"
copyright = "© 2022-2023, Austin Bullock & Andrew Wasserbeck"

[build]
auto-executables = true
auto-tests = true
auto-examples = true

[install]
library = false

[dependencies]
IO-Fortran-Library = { git="https://github.com/acbbullock/IO-Fortran-Library", branch="main" }
